# Generated by Django 4.2.4 on 2023-08-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenescreadas',
            name='nombreImagen',
            field=models.CharField(default='ValorPorDefecto', max_length=250),
        ),
        migrations.AlterField(
            model_name='imagenescreadas',
            name='urlImagen',
            field=models.URLField(max_length=255),
        ),
    ]
