# Generated by Django 4.2.4 on 2023-08-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_imagenescreadas_nombreimagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
