# Generated by Django 4.2.4 on 2023-08-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenescreadas',
            name='idUsuario',
        ),
    ]
