# Generated by Django 4.2.4 on 2023-08-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_imagenescreadas_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenescreadas',
            name='idUsuario',
        ),
    ]
