# Generated by Django 4.2.4 on 2023-08-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_imagenescreadas_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenescreadas',
            name='urlImagen',
            field=models.URLField(max_length=555),
        ),
    ]
