# Generated by Django 4.2.4 on 2023-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_imagenescreadas_urlimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenescreadas',
            name='urlImagen',
            field=models.URLField(max_length=1055),
        ),
    ]
