# Generated by Django 4.2.4 on 2023-08-28 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_imagenescreadas_idusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenescreadas',
            name='idUsuario',
        ),
    ]
