# Generated by Django 4.2.4 on 2023-08-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_imagenescreadas_idusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenescreadas',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
