# Generated by Django 4.2.4 on 2023-08-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_imagenescreadas_idusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenescreadas',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='imagenescreadas',
            name='nombreImagen',
            field=models.CharField(max_length=250),
        ),
    ]
