# Generated by Django 4.2.4 on 2023-08-28 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_imagenescreadas_idusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenescreadas',
            name='idUsuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
        migrations.AlterField(
            model_name='imagenescreadas',
            name='nombreImagen',
            field=models.CharField(default='ValorPorDefecto', max_length=250),
        ),
    ]
