# Generated by Django 4.2.4 on 2023-09-11 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_imagenescreadas_idusuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajesdiarios',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
