# Generated by Django 4.2.4 on 2023-09-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_mensajesdiarios_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mensaje_diario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
