# Generated by Django 4.2.4 on 2023-09-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cancionescreadas_letracancion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipsqueledigo',
            name='respuestaAI',
            field=models.TextField(default='respuesta'),
        ),
    ]
