# Generated by Django 4.2.4 on 2023-10-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_tipsqueledigo_respuestaai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comidascreadas',
            old_name='fecha',
            new_name='fechas',
        ),
        migrations.AddField(
            model_name='comidascreadas',
            name='ingredientes',
            field=models.TextField(default='pollo,papa'),
        ),
        migrations.AlterField(
            model_name='comidascreadas',
            name='nombreComida',
            field=models.CharField(max_length=100),
        ),
    ]
